"""link holdings to instruments

Revision ID: 4d6f5801f71c
Revises: 8f80e18a9080
Create Date: 2026-09-28 23:39:09.742003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d6f5801f71c"
down_revision: Union[str, Sequence[str], None] = "8f80e18a9080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("holdings", sa.Column("instrument_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_holdings_instrument_id"), "holdings", ["instrument_id"], unique=False
    )
    op.create_foreign_key(
        "fk_holdings_instrument_id",
        "holdings",
        "instruments",
        ["instrument_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "fk_holdings_instrument_id",
        "holdings",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_holdings_instrument_id"),
        table_name="holdings",
    )
    op.drop_column("holdings", "instrument_id")
