"""require instrument for holdings

Revision ID: 4f296ed4d1b7
Revises: 82074cabddd3
Create Date: 2026-09-28 23:49:14.584597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f296ed4d1b7'
down_revision: Union[str, Sequence[str], None] = '82074cabddd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holdings', 'instrument_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holdings', 'instrument_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
