"""add instruments table

Revision ID: 8f80e18a9080
Revises: 6b49057318da
Create Date: 2026-09-28 01:00:33.655432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f80e18a9080'
down_revision: Union[str, Sequence[str], None] = '6b49057318da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('trading_symbol', sa.String(length=50), nullable=False),
    sa.Column('groww_symbol', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('exchange_token', sa.String(length=50), nullable=False),
    sa.Column('instrument_type', sa.String(length=30), nullable=False),
    sa.Column('segment', sa.String(length=30), nullable=False),
    sa.Column('series', sa.String(length=20), nullable=True),
    sa.Column('lot_size', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groww_symbol'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_instruments_trading_symbol'), 'instruments', ['trading_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_trading_symbol'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
