"""remove company name from holdings

Revision ID: a7cf0760b310
Revises: 4f296ed4d1b7
Create Date: 2026-09-29 00:27:31.595076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7cf0760b310'
down_revision: Union[str, Sequence[str], None] = '4f296ed4d1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
